apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-geo
  name: mongodb-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-geo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-geo
    spec:
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-geo-mongo
          ports:
            - containerPort: 27017
          # resources:
          #   requests:
          #     cpu: 100m
          #   limits:
          #     cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: geo
      restartPolicy: Always
      volumes:
        - name: geo
          persistentVolumeClaim:
            claimName: geo-pvc
        - name: tmp
          emptyDir: {}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                io.kompose.service: geo
            topologyKey: "kubernetes.io/hostname"
status: {}
