apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend2
  name: frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        io.kompose.service: frontend2
    spec:
      containers:
        - command:
            - /go/bin/frontend2
          image: docker.io/alicesong2002/hotel-reservation-modified:v1.8
          name: hotel-reserv-frontend2
          ports:
            - containerPort: 5001
          # resources:
          #   requests:
          #     cpu: 100m
          #   limits:
          #     cpu: 1000m
          securityContext:
            runAsUser: 0
            privileged: true
      restartPolicy: Always
status: {}