apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hotel
  labels:
    io.kompose.service: frontend
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend

  template:
    metadata:
      labels:
        io.kompose.service: frontend
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: >
          cluster.outbound,cluster_manager,listener_manager,
          http_mixer_filter,tcp_mixer_filter,server,
          cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*

    spec:
      restartPolicy: Always

      containers:
        # -----------------------------
        # Frontend application container
        # -----------------------------
        - name: hotel-reserv-frontend
          image: docker.io/alicesong2002/hotel-reservation-modified:v1.2
          command:
            - /go/bin/frontend
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]

        - name: opa
          image: openpolicyagent/opa:latest-envoy
          args:
            - run
            - --server
            - --addr=0.0.0.0:8181
            - --log-level=info
            - --set=plugins.envoy_ext_authz_grpc.addr=:9191
            - --set=plugins.envoy_ext_authz_grpc.path=istio/authz/allow
            - /policy
          ports:
            - name: http
              containerPort: 8181
            - name: grpc
              containerPort: 9191
          volumeMounts:
            - name: opa-policy
              mountPath: /policy
              readOnly: true

        - name: istio-proxy
          image: docker.io/alicesong2002/modified_istio_proxy:v19.3
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
            - name: linux-headers
              mountPath: /usr/src
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "3000Mi"
            limits:
              memory: "3000Mi"

      volumes:
        - name: tmp
          emptyDir: {}

        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory

        - name: linux-headers
          hostPath:
            path: /usr/src
            type: Directory

        - name: opa-policy
          configMap:
            name: opa-policy